# project definitions
project: doc
audience: all 
product: all
platform: all
version: all
destination: ../doc_designers
topnav_title: Stanford CoreNLP
homepage_title: Stanford CoreNLP &ndash; Core natural language software
site_title: Stanford CoreNLP
#disqus_shortname: idrbwjekyll
#google_analytics: UA-66296557-1

# variables

sidebar_tagline: CoreNLP
sidebar_version: version 3.8.0
project_file_name: doc
company_name: Stanford NLP

port: 4001

exclude:
  - doc_writer*
  - configs/
  - _site
  - di_multi*

include:
  - _pages

# avoid https mixed content?
url: https://stanfordnlp.github.io
# same for all
host: 127.0.0.1
sidebar_accordion: true
markdown: kramdown
print: false
theme_file: theme-cardinal.css
# only use suffix if you need to force index.html to display
# suffix: index.html

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]

highlighter: rouge

collections:
  tooltips:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true

