name: Run Slow Tests
on: [push]
concurrency: slow-itests
jobs:
  Run-CoreNLP-Slow-Tests:
    runs-on: self-hosted
    timeout-minutes: 2880
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Setup
        run: |
          pwd
          ant clean compile
          echo $CLASSPATH
          echo $PATH
      - name: Run Misc Slow Tests
        if: always()
        run: |
          ant itest-misc
      - name: Run KBP Tests
        if: always()
        run: |
          ant itest-kbp
      - name: Run NER Tests
        if: always()
        run: |
          ant itest-ner
      - name: Run Coref Tests
        if: always()
        run: |
          ant itest-coreference
      - name: Run Many Docs Tests
        if: always()
        run: |
          ant itest-many-docs
      - name: Run Protobuf Slow Test
        if: always()
        run: |
          ant itest-protobuf
      - run: echo "All tests finished!"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
